//
//  countries.swift
//  DigiDoe Business Banking
//
//  Created by Настя Оксенюк on 26.01.2024.
//

import Foundation

let countryCodes: Array<Option> = [
    Option(id: "AL", label: "Albania"),
    Option(id: "DZ", label: "Algeria"),
    Option(id: "AS", label: "American Samoa"),
    Option(id: "AD", label: "Andorra"),
    Option(id: "AO", label: "Angola"),
    Option(id: "AI", label: "Anguilla"),
    Option(id: "AQ", label: "Antarctica"),
    Option(id: "AG", label: "Antigua and Barbuda"),
    Option(id: "AR", label: "Argentina"),
    Option(id: "AM", label: "Armenia"),
    Option(id: "AW", label: "Aruba"),
    Option(id: "AU", label: "Australia"),
    Option(id: "AT", label: "Austria"),
    Option(id: "AZ", label: "Azerbaijan"),
    Option(id: "BS", label: "Bahamas"),
    Option(id: "BH", label: "Bahrain"),
    Option(id: "BD", label: "Bangladesh"),
    Option(id: "BB", label: "Barbados"),
    Option(id: "BY", label: "Belarus"),
    Option(id: "BE", label: "Belgium"),
    Option(id: "BZ", label: "Belize"),
    Option(id: "BJ", label: "Benin"),
    Option(id: "BM", label: "Bermuda"),
    Option(id: "BT", label: "Bhutan"),
    Option(id: "BO", label: "Bolivia"),
    Option(id: "BQ", label: "Bonaire"),
    Option(id: "BA", label: "Bosnia and Herzegovina"),
    Option(id: "BW", label: "Botswana"),
    Option(id: "BV", label: "Bouvet Island"),
    Option(id: "BR", label: "Brazil"),
    Option(id: "IO", label: "British Indian Ocean Territory"),
    Option(id: "VG", label: "British Virgin Islands"),
    Option(id: "BN", label: "Brunei Darussalam"),
    Option(id: "BG", label: "Bulgaria"),
    Option(id: "BF", label: "Burkina Faso"),
    Option(id: "KH", label: "Cambodia"),
    Option(id: "CM", label: "Cameroon"),
    Option(id: "CA", label: "Canada"),
    Option(id: "CV", label: "Cape Verde"),
    Option(id: "KY", label: "Cayman Islands"),
    Option(id: "CL", label: "Chile"),
    Option(id: "CN", label: "China"),
    Option(id: "CX", label: "Christmas Island"),
    Option(id: "CC", label: "Cocos (Keeling) Islands"),
    Option(id: "CO", label: "Colombia"),
    Option(id: "KM", label: "Comoros"),
    Option(id: "CK", label: "Cook Islands"),
    Option(id: "CR", label: "Costa Rica"),
    Option(id: "HR", label: "Croatia"),
    Option(id: "CW", label: "Curaçao"),
    Option(id: "CY", label: "Cyprus"),
    Option(id: "CZ", label: "Czech Republic"),
    Option(id: "CI", label: "Côte d\'\'Ivoire"),
    Option(id: "DK", label: "Denmark"),
    Option(id: "DJ", label: "Djibouti"),
    Option(id: "DM", label: "Dominica"),
    Option(id: "DO", label: "Dominican Republic"),
    Option(id: "EC", label: "Ecuador"),
    Option(id: "EG", label: "Egypt"),
    Option(id: "SV", label: "El Salvador"),
    Option(id: "GQ", label: "Equatorial Guinea"),
    Option(id: "EE", label: "Estonia"),
    Option(id: "ET", label: "Ethiopia"),
    Option(id: "FK", label: "Falkland Islands"),
    Option(id: "FO", label: "Faroe Islands"),
    Option(id: "FJ", label: "Fiji"),
    Option(id: "FI", label: "Finland"),
    Option(id: "FR", label: "France"),
    Option(id: "GF", label: "French Guiana"),
    Option(id: "PF", label: "French Polynesia"),
    Option(id: "TF", label: "French Southern Territories"),
    Option(id: "GA", label: "Gabon"),
    Option(id: "GM", label: "Gambia"),
    Option(id: "GE", label: "Georgia"),
    Option(id: "DE", label: "Germany"),
    Option(id: "GH", label: "Ghana"),
    Option(id: "GI", label: "Gibraltar"),
    Option(id: "GR", label: "Greece"),
    Option(id: "GL", label: "Greenland"),
    Option(id: "GD", label: "Grenada"),
    Option(id: "GP", label: "Guadeloupe"),
    Option(id: "GU", label: "Guam"),
    Option(id: "GT", label: "Guatemala"),
    Option(id: "GG", label: "Guernsey"),
    Option(id: "GN", label: "Guinea"),
    Option(id: "GW", label: "Guinea-Bissau"),
    Option(id: "GY", label: "Guyana"),
    Option(id: "HT", label: "Haiti"),
    Option(id: "HM", label: "Heard Island and McDonald Islands"),
    Option(id: "HN", label: "Honduras"),
    Option(id: "HK", label: "Hong Kong"),
    Option(id: "HU", label: "Hungary"),
    Option(id: "IS", label: "Iceland"),
    Option(id: "IN", label: "India"),
    Option(id: "ID", label: "Indonesia"),
    Option(id: "IE", label: "Ireland"),
    Option(id: "IM", label: "Isle of Man"),
    Option(id: "IL", label: "Israel"),
    Option(id: "IT", label: "Italy"),
    Option(id: "JM", label: "Jamaica"),
    Option(id: "JP", label: "Japan"),
    Option(id: "JE", label: "Jersey"),
    Option(id: "JO", label: "Jordan"),
    Option(id: "KZ", label: "Kazakhstan"),
    Option(id: "KE", label: "Kenya"),
    Option(id: "KI", label: "Kiribati"),
    Option(id: "XK", label: "Kosovo, Republic of"),
    Option(id: "KW", label: "Kuwait"),
    Option(id: "KG", label: "Kyrgyzstan"),
    Option(id: "LA", label: "Laos"),
    Option(id: "LV", label: "Latvia"),
    Option(id: "LB", label: "Lebanon"),
    Option(id: "LS", label: "Lesotho"),
    Option(id: "LR", label: "Liberia"),
    Option(id: "LI", label: "Liechtenstein"),
    Option(id: "LT", label: "Lithuania"),
    Option(id: "LU", label: "Luxembourg"),
    Option(id: "MO", label: "Macao"),
    Option(id: "MK", label: "Macedonia, Former Yugoslav Republic of"),
    Option(id: "MG", label: "Madagascar"),
    Option(id: "MW", label: "Malawi"),
    Option(id: "MY", label: "Malaysia"),
    Option(id: "MV", label: "Maldives"),
    Option(id: "ML", label: "Mali"),
    Option(id: "MT", label: "Malta"),
    Option(id: "MH", label: "Marshall Islands"),
    Option(id: "MQ", label: "Martinique"),
    Option(id: "MR", label: "Mauritania"),
    Option(id: "MU", label: "Mauritius"),
    Option(id: "YT", label: "Mayotte"),
    Option(id: "MX", label: "Mexico"),
    Option(id: "FM", label: "Micronesia, Federated States of"),
    Option(id: "MD", label: "Moldova"),
    Option(id: "MC", label: "Monaco"),
    Option(id: "MN", label: "Mongolia"),
    Option(id: "ME", label: "Montenegro"),
    Option(id: "MS", label: "Montserrat"),
    Option(id: "MA", label: "Morocco"),
    Option(id: "MZ", label: "Mozambique"),
    Option(id: "MM", label: "Myanmar"),
    Option(id: "NA", label: "Namibia"),
    Option(id: "NR", label: "Nauru"),
    Option(id: "NP", label: "Nepal"),
    Option(id: "NL", label: "Netherlands"),
    Option(id: "AN", label: "Netherlands Antilles"),
    Option(id: "NC", label: "New Caledonia"),
    Option(id: "NZ", label: "New Zealand"),
    Option(id: "NI", label: "Nicaragua"),
    Option(id: "NE", label: "Niger"),
    Option(id: "NG", label: "Nigeria"),
    Option(id: "NU", label: "Niue"),
    Option(id: "NF", label: "Norfolk Island"),
    Option(id: "MP", label: "Northern Mariana Islands"),
    Option(id: "NO", label: "Norway"),
    Option(id: "OM", label: "Oman"),
    Option(id: "PK", label: "Pakistan"),
    Option(id: "PW", label: "Palau"),
    Option(id: "PS", label: "Palestine"),
    Option(id: "PA", label: "Panama"),
    Option(id: "PG", label: "Papua New Guinea"),
    Option(id: "PY", label: "Paraguay"),
    Option(id: "PE", label: "Peru"),
    Option(id: "PH", label: "Philippines"),
    Option(id: "PN", label: "Pitcairn Islands"),
    Option(id: "PL", label: "Poland"),
    Option(id: "PT", label: "Portugal"),
    Option(id: "PR", label: "Puerto Rico"),
    Option(id: "QA", label: "Qatar"),
    Option(id: "RO", label: "Romania"),
    Option(id: "RU", label: "Russian Federation"),
    Option(id: "RW", label: "Rwanda"),
    Option(id: "RE", label: "Réunion"),
    Option(id: "BL", label: "Saint Barthélemy"),
    Option(id: "SH", label: "Saint Helena"),
    Option(id: "KN", label: "Saint Kitts and Nevis"),
    Option(id: "LC", label: "Saint Lucia"),
    Option(id: "MF", label: "Saint Martin (French part)"),
    Option(id: "PM", label: "Saint Pierre and Miquelon"),
    Option(id: "VC", label: "Saint Vincent and the Grenadines"),
    Option(id: "WS", label: "Samoa"),
    Option(id: "SM", label: "San Marino"),
    Option(id: "ST", label: "Sao Tome and Principe"),
    Option(id: "SA", label: "Saudi Arabia"),
    Option(id: "SN", label: "Senegal"),
    Option(id: "RS", label: "Serbia"),
    Option(id: "SC", label: "Seychelles"),
    Option(id: "SL", label: "Sierra Leone"),
    Option(id: "SG", label: "Singapore"),
    Option(id: "SX", label: "Sint Maarten (Dutch part)"),
    Option(id: "SK", label: "Slovakia"),
    Option(id: "SI", label: "Slovenia"),
    Option(id: "SB", label: "Solomon Islands"),
    Option(id: "ZA", label: "South Africa"),
    Option(id: "GS", label: "South Georgia and the South Sandwich Islands"),
    Option(id: "KR", label: "South Korea"),
    Option(id: "ES", label: "Spain"),
    Option(id: "LK", label: "Sri Lanka"),
    Option(id: "SR", label: "Surivalue"),
    Option(id: "SJ", label: "Svalbard and Jan Mayen"),
    Option(id: "SZ", label: "Swaziland"),
    Option(id: "SE", label: "Sweden"),
    Option(id: "CH", label: "Switzerland"),
    Option(id: "TW", label: "Taiwan"),
    Option(id: "TJ", label: "Tajikistan"),
    Option(id: "TZ", label: "Tanzania"),
    Option(id: "TH", label: "Thailand"),
    Option(id: "TL", label: "Timor-Leste"),
    Option(id: "TG", label: "Togo"),
    Option(id: "TK", label: "Tokelau"),
    Option(id: "TO", label: "Tonga"),
    Option(id: "TT", label: "Trinidad and Tobago"),
    Option(id: "TN", label: "Tunisia"),
    Option(id: "TR", label: "Turkey"),
    Option(id: "TM", label: "Turkmenistan"),
    Option(id: "TC", label: "Turks and Caicos Islands"),
    Option(id: "TV", label: "Tuvalu"),
    Option(id: "UG", label: "Uganda"),
    Option(id: "UA", label: "Ukraine"),
    Option(id: "AE", label: "United Arab Emirates"),
    Option(id: "GB", label: "United Kingdom"),
    Option(id: "US", label: "United States"),
    Option(id: "UM", label: "United States Minor Outlying Islands"),
    Option(id: "VI", label: "United States Virgin Islands"),
    Option(id: "UY", label: "Uruguay"),
    Option(id: "UZ", label: "Uzbekistan"),
    Option(id: "VU", label: "Vanuatu"),
    Option(id: "VA", label: "Vatican City"),
    Option(id: "VN", label: "Vietnam"),
    Option(id: "WF", label: "Wallis and Futuna"),
    Option(id: "EH", label: "Western Sahara"),
    Option(id: "ZM", label: "Zambia"),
    Option(id: "ZW", label: "Zimbabwe"),
    Option(id: "AX", label: "Åland Islands")
]
